DROP TABLE BG_EPILOGUE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BG_EPILOGUE;

CREATE TABLE BG_EPILOGUE(
    SEQ NUMBER(8) PRIMARY KEY,               
    ID VARCHAR2(50) NOT NULL, 
    REF NUMBER(8) NOT NULL,
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
    THUMBNAIL VARCHAR2(200) NOT NULL,     
    TITLE VARCHAR2(200) NOT NULL,  
    CONTENT VARCHAR2(4000) NOT NULL, 
    WDATE DATE NOT NULL, 
    DEL NUMBER(1) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL                     
);

CREATE SEQUENCE SEQ_BG_EPILOGUE
START WITH 1
INCREMENT BY 1;

ALTER TABLE BG_EPILOGUE
ADD CONSTRAINT FK_BG_EPILOGUE_ID FOREIGN KEY(ID)
REFERENCES BG_MEMBER(ID);

SELECT * FROM BG_EPILOGUE;
SELECT COUNT(REF) FROM BG_EPILOGUE WHERE REF=5;
SELECT * FROM BG_EPILOGUE  WHERE REF = 1;
SELECT * FROM BG_EPILOGUE  WHERE  REF = 1  AND  THUMBNAIL <> 'Main' ;
