INSERT INTO BG_MEMBER(SEQ, ID, PW, CALL_NUMBER, NAME, EMAIL, BONUSCREDIT, REGDATE, AUTH, DEL)
VALUES(1, 'qqq', 'qqq', '01012345678', '관리자테스트', 'adlf@naver.com', 1000, SYSDATE, 1, 0);

SELECT * FROM BG_MEMBER